### ISSUE TITLE
Issue with model alias unrealated to model name in schema

### ISSUE THREAD

**Issue by faboo03** [xavierlacot/sfDoctrineRestGeneratorPlugin#1]
Hi, 

I am figuring en issue in validators array during generation. 
I explain my case: 

schema.yml : 

  PiAbonnement:
    columns:
      id: { type: integer, primary: true, autoincrement: true }
       ~~
    relations:
      annonce:
        local: id
        foreign: abonnement_id
        class: PiAnnonce
        onDelete: CASCADE

  PiAnnonce:
    columns:
      id: {type: integer, primary: true, autoincrement: true}
    relations:
      abonnement:
        type: one
        local: abonnement_id
        foreign: id
        class: PiAbonnement

As you can see, Annonce relation with Abonnement as this difference: Alias and Model Name are differente. 

So when I am generating a new module I get in the autoAnnonceActions : 
 public function getCreateValidators()
  {
    return array(
'abonnement_id' => new sfValidatorDoctrineChoice(array('model' => Doctrine_Core::getTable('PiAnnonce')->getRelation('abonnement')->getAlias(), 'required' => false)),

And the error "Couldn't find annonce class"... 

Obviously there is a mistake in "Doctrine_Core::getTable('PiAnnonce')->getRelation('abonnement')->getAlias()" because we should have "Doctrine_Core::getTable('PiAnnonce')->getRelation('abonnement')->getClass()"

I hope I have been clear enought to simplify your debugging work! 

By the way, to correct it: 

in /lib/generator/sfDoctrineRestGenerator.class.php : 
line 744 : changing "Alias" by "Class" 

 $options[] = sprintf('\'model\' => Doctrine_Core::getTable('.$model.')->getRelation(\'%s\')->getClass()', $column->getRelationKey('alias'));

This do the job, but maybe i am missing something...

**Comment by javyer** [comment]
I can confirm this issue, i found the same solution, replacing getAlias by getClass on :
--- lib/generator/sfDoctrineRestGenerator.class.php (révision 33105)
+++ lib/generator/sfDoctrineRestGenerator.class.php (copie de travail)
@@ -741,7 +741,7 @@

```
 if ($column->isForeignKey())
 {
```
-      $options[] = sprintf('\'model\' => Doctrine_Core::getTable('.$model.')->getRelation(\'%s\')->getAlias()', $column->getRelationKey('alias'));
-      $options[] = sprintf('\'model\' => Doctrine_Core::getTable('.$model.')->getRelation(\'%s\')->getClass()', $column->getRelationKey('alias'));
   }
   else if ($column->isPrimaryKey())
   {
