### ISSUE TITLE
Calls reversed in sfDoctrineRestGenerator::underscorePayload?

### ISSUE THREAD

**Issue by fentie** [xavierlacot/sfDoctrineRestGeneratorPlugin#2]
Just wanted to make sure I'm not the only one running into this.

Currently the referenced method runs this bit of code if the payload parameter is not an array:

if (!is_array($value))
{
      $value = trim((string)$value);
      $underscored_name = sfInflector::underscore($name);
      $payload_array[$underscored_name] = $value;
      unset($payload_array[$name]);
}

Shouldn't the unset and $payload_array assignment be reversed? Otherwise, when passed a parameter like "title" => "Department of Dance", $underscored_name and $name are both equal. That means that $payload_array['title'] is set and then unset on the next line, resulting in a missing parameter. I verified this by passing in "Title" instead and the parameter then showed up correctly in my output. 

If I'm doing something wrong let me know, otherwise I'll be happy to submit a pull request. Thanks.

**Comment by paddoum** [comment]
Hi,

I had the same issue and solve it the same way.

Pierre

**Comment by xavierlacot** [comment]
This has been closed in #6
