### ISSUE TITLE
POST issue when testing with curl

### ISSUE THREAD

**Issue by paddoum** [xavierlacot/sfDoctrineRestGeneratorPlugin#3]
Hi Xavier,

Thanks for this great plugin.

I'm struggling getting POST method to work and when I test my service with curl I receive an error message I

curl -i -H "Accept:application/json" -H "Content-Type:application/
json"  -d [{"name":"new"}] http://mywebsite.com/api.php/region

{"message":"Could not parse payload, obviously not a valid json
data!"}

Thanks in advance for your help.
Pierre

**Comment by xavierlacot** [comment]
The right syntax for creating unitary items is the following, without brackets:
curl -i -H "Accept:application/json" -H "Content-Type:application/json" -d '{"name":"new"}' http://mywebsite.com/api.php/region

**Comment by paddoum** [comment]
Thanks Xavier!
