### ISSUE TITLE
different behaviour when updating and creating

### ISSUE THREAD

**Issue by cured** [xavierlacot/sfDoctrineRestGeneratorPlugin#7]
check this code:

  public function executeUpdate(sfWebRequest $request)
  {
    $this->forward404Unless($request->isMethod(sfRequest::PUT));
    $content = $request->getContent();

and this:

  public function executeCreate(sfWebRequest $request)
  {
    $this->forward404Unless($request->isMethod(sfRequest::POST));
    $content = $request->getParameter('content');

should they be the same?

**Comment by cured** [comment]
i mean how the content variable is initialized

**Comment by xavierlacot** [comment]
This was fixed in https://github.com/xavierlacot/sfDoctrineRestGeneratorPlugin/commit/ed413a473ba010d3b8b693f8872d9d3b542e62d2
