### ISSUE TITLE
Problem with jQuery POST

### ISSUE THREAD

**Issue by DanAKAHollywood** [xavierlacot/sfDoctrineRestGeneratorPlugin#9]
I have the following function:

function addCustomer() {
            $.ajax({
                type: 'POST',
                url: '/api.php/customers.json',
                async: false,
                data: '{' +
                    '"id": "0", ' +
                    '"customername": ' + '"'+$('#customer-name').val()+'"' + ', ' +
                    '"streetaddress": ' + '"'+$('#customer-address').val()+'"' + ', ' +
                    '"city": ' + '"'+$('#customer-city').val()+'"' + ', ' +
                    '"stateid": ' + '"'+$('#customer-stateid').val()+'"' + ', ' +
                    '"zip": ' + '"'+$('#customer-zip').val()+'"' + ', ' +
                    '"countryid": ' + '"'+$('#customer-countryid').val()+'"' +
                    '}',
                success: function(data) {
                    alert('Success!');
                },
                dataType: 'json'
            });
        }

I always receive the following response and it is causing me to lose sleep!!

[{"message":"Could not parse payload, obviously not a valid json data!"}]

I have tried several variations of the data and many other things to no avail. I need assistance from a guru!

**Comment by xavierlacot** [comment]
What about passing a real javascript array to the `ajax()` method, instead of a json-like string? For example:

```
function addCustomer() {
    $.ajax({
        type: 'POST',
        url: '/api.php/customers.json',
        async: false,
        data: {
            id: 0,
            customername: $('#customer-name').val(),
            streetaddress: $('#customer-address').val(),
            city: $('#customer-city').val(),
            stateid: $('#customer-stateid').val(),
            zip: $('#customer-zip').val(),
            countryid: $('#customer-countryid').val()
        },
        success: function(data) {
            alert('Success!');
        },
        dataType: 'json'
    });
}
```

If that doesn't work, check the code generated in `cache/YOUR_APPLICATION/prod/modules/autoYOUR_MODEL/actions/actions.class.php`. Have a look at the method `parsePayload()`, possibly log the value of the `$payload` variable. It should be a valid json string. If you are uncertain, check the value of `$payload_array`, which should be an array. If not, then something goes wrong when posting the data to the service.

**Comment by DanAKAHollywood** [comment]
I had originally tried passing a JS array and got the same response. I will take a look at the payload and see if I can figure out where I am going wrong.

**Comment by DanAKAHollywood** [comment]
The payload is never making it to validateCreate. Any ideas?

**Comment by DanAKAHollywood** [comment]
Here is my latest:

``` javascript
function addCustomer() {
            $.ajax({
                type: 'POST',
                url: '/api.php/customers.json',
                async: false,
                data: { 
                    content: '{' +
                        '"id": "0", ' +
                        '"customername": ' + '"'+$('#customer-name').val()+'"' + ', ' +
                        '"streetaddress": ' + '"'+$('#customer-address').val()+'"' + ', ' +
                        '"city": ' + '"'+$('#customer-city').val()+'"' + ', ' +
                        '"stateid": ' + '"'+$('#customer-stateid').val()+'"' + ', ' +
                        '"zip": ' + '"'+$('#customer-zip').val()+'"' + ', ' +
                        '"countryid": ' + '"'+$('#customer-countryid').val()+'"' +
                    '}'
                },
                success: function(data) {
                    alert('Success!');
                },
                dataType: 'json'
            });
        }
```

Response:

[{"message":"Could not validate field \"customername\": Required."}]

I have tried passing an array, various forms of json and this is the only way I have been able to successfully get the payload to the action. I'm not sure exactly where I'm going wrong considering that customername is valid according to the BaseCustomersGenerator class.

**Comment by xavierlacot** [comment]
What about the $payload_array var, which represents the de-serialization of
the json data sent through the request? Is it an array with a "customername"
key in it?

On Tue, Aug 23, 2011 at 4:56 PM, DanAKAHollywood <
reply@reply.github.com>wrote:

> Here is my latest:
> 
> ``` javascript
> function addCustomer() {
>                        $.ajax({
>                                type: 'POST',
>                                url: '/api.php/customers.json',
>                                async: false,
>                                 data: {
>                                        content: '{' +
>                                                 '"id": "0", ' +
>                                                '"customername": ' +
> '"'+$('#customer-name').val()+'"' + ', ' +
>                                                '"streetaddress": ' +
> '"'+$('#customer-address').val()+'"' + ', ' +
>                                                '"city": ' +
> '"'+$('#customer-city').val()+'"' + ', ' +
>                                                '"stateid": ' +
> '"'+$('#customer-stateid').val()+'"' + ', ' +
>                                                '"zip": ' +
> '"'+$('#customer-zip').val()+'"' + ', ' +
>                                                '"countryid": ' +
> '"'+$('#customer-countryid').val()+'"' +
>                                        '}'
>                                },
>                                success: function(data) {
>                                        alert('Success!');
>                                },
>                                dataType: 'json'
>                        });
>                }
> ```
> 
> Response:
> 
> [{"message":"Could not validate field \"customername\": Required."}]
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/xavierlacot/sfDoctrineRestGeneratorPlugin/issues/9#issuecomment-1880545

## 

Xavier Lacot
xavier@lacot.org
http://lacot.org/

**Comment by DanAKAHollywood** [comment]
I had it throw an exception in parsePayload with print_r($payload_array, true) and this is the output I got.

[{"message":"Array holds: Array\n(\n    [id] => 0\n    [customername] => test\n    [streetaddress] => test\n    [city] => test\n    [stateid] => 1868\n    [zip] => 12345\n    [countryid] => 218\n)\n"}]

**Comment by DanAKAHollywood** [comment]
The payload is valid, however, $params is empty in validate(...). Not sure how that happens.

It appears that whatever is going wrong is happening in underscorePayload(...) as $this->_payload_array is ending up null after that call.

**Comment by xavierlacot** [comment]
There is no way the payload is parsed well and the $params array passed to validate() is empty. Are you sure that you are using the latest and unmodified version of the plugin? A bug affecting the payload cleanup was fixed in https://github.com/xavierlacot/sfDoctrineRestGeneratorPlugin/commit/3c84ee21b6dc3eb82c023fc7ae8567a89d02e159

Here is the code of the `parsePayload()` method that should have been generated:

```
  protected function parsePayload($payload, $force = false)
  {
    if ($force || !isset($this->_payload_array))
    {
      $format = $this->getFormat();
      $serializer = $this->getSerializer();

      if ($serializer)
      {
        $payload_array = $serializer->unserialize($payload);
      }

      if (!isset($payload_array) || !$payload_array)
      {
        throw new sfException(sprintf('Could not parse payload, obviously not a valid %s data!', $format));
      }

      $filter_params = array ();
      $this->_payload_array = sfDoctrineRestGenerator::underscorePayload($payload_array, $filter_params);
    }

    return $this->_payload_array;
  }
```

Please check the value of `$this->_payload_array` after the call to `sfDoctrineRestGenerator::underscorePayload`. If it is empty while $payload_array contains values, then there must be a bug in `sfDoctrineRestGenerator::underscorePayload` (or you are not using the latest version of the plugin available from GitHub).

**Comment by DanAKAHollywood** [comment]
The parsePayload matches what you provided above and this is an unmodified copy of the plugin that I downloaded last week. Here is the output of the $payload_array and $this->_payload_array just before the return. As you can see, one is populated while the other is empty, after the underscorePayload call.

[{"message":"payload_array: Array\n(\n    [customername] => test\n    [streetaddress] => test\n    [city] => test\n    [stateid] => 1868\n    [zip] => 12345\n    [countryid] => 218\n)\n | _payload_array: Array\n(\n)\n"}]

**Comment by DanAKAHollywood** [comment]
Scratch that. I'm not sure why my copy wasn't right but looking at the bugfix you mentioned (https://github.com/xavierlacot/sfDoctrineRestGeneratorPlugin/commit/3c84ee21b6dc3eb82c023fc7ae8567a89d02e159), I noticed mine was different. I made the change accordingly and now all is well.

**Comment by DanAKAHollywood** [comment]
The one last thing that I'm curious about. Is there a way to get the primary key of the row I just inserted?

**Comment by xavierlacot** [comment]
Hum, nope with the default version, as the create action returns an empty content. But you may overload the doSave() method in order to return a serialization of the newly created object. I did not test it, but sthing like this should work:

```
protected function doSave()
{
  $this->object->save();
  $serializer = $this->getSerializer();
  $this->getResponse()->setContentType($serializer->getContentType());
  $this->output = $serializer->serialize($this->object, $this->model);
  $this->setTemplate('index');
  return sfView::SUCCESS;
}
```

As for the plugin's version, you may want to download a completely fresh version from https://github.com/xavierlacot/sfDoctrineRestGeneratorPlugin/tarball/master

**Comment by DanAKAHollywood** [comment]
That returns { }. Just by looking at it, it seems like it would work...

**Comment by DanAKAHollywood** [comment]
Superbly ugly but this returns the id for me:

``` php
protected function doSave() {
    $this->object->save();
    print_r(sprintf('{"id": "%s"}', $this->object->get('id')));
    $this->setTemplate('index');
    return sfView::SUCCESS;
}
```

Would you mind making the plugin return the last inserted object as the default action? I think that would be a very handy feature to have; especially for use with ajax calls.
